import { BattleTreeRewardPool, BattleTreeRewardPoolNameType } from './BattleTreeRewardPool';
import MaxRegionRequirement from '../../../requirements/MaxRegionRequirement';
import { Region } from '../../../GameConstants';

export const BattleTreeRewardPools: Partial<Record<BattleTreeRewardPoolNameType, BattleTreeRewardPool>> = {
    generic: new BattleTreeRewardPool({
        id: 'generic',
        entries: [
            { item: 'Pokeball', weight: 100, amount: { min: 5, max: 10 } },
            { item: 'Greatball', weight: 50, amount: { min: 2, max: 5 } },
            { item: 'Ultraball', weight: 10, amount: { min: 1, max: 3 } },
            { item: 'Masterball', weight: 1, amount: 1 },
            { item: new BattleTreeRewardPool({
                id: 'mega_rare',
                entries: [
                    { item: 'Heat_rock', weight: 99, amount: 1 },
                    { item: 'Heat_rock', weight: 1, amount: 1000 },
                ],
            }), weight: 1, amount: 1 },
        ],
    }),
    special_ball: new BattleTreeRewardPool({
        id: 'special_ball',
        entries: [
            { item: 'Fastball', weight: 1, amount: 1 },
            { item: 'Quickball', weight: 1, amount: 1 },
            { item: 'Timerball', weight: 1, amount: 1 },
            { item: 'Duskball', weight: 1, amount: 1 },
            { item: 'Luxuryball', weight: 1, amount: 1 },
            { item: 'Diveball', weight: 1, amount: 1 },
            { item: 'Lureball', weight: 1, amount: 1 },
            { item: 'Nestball', weight: 1, amount: 1 },
            { item: 'Repeatball', weight: 1, amount: 1 },
            { item: 'Beastball', weight: 1, amount: 1 },
            { item: 'Moonball', weight: 1, amount: 1 },
        ],
    }),
    currency: new BattleTreeRewardPool({
        id: 'currency',
        entries: [
            { item: 'Money', weight: 1, amount: 30000 },
            { item: 'Quest Point', weight: 1, amount: 90 },
            { item: 'Dungeon Token', weight: 1, amount: 1500 },
            { item: 'Diamond', weight: 1, amount: 150 },
            { item: 'Farm Point', weight: 1, amount: 90 },
            { item: 'Battle Point', weight: 1, amount: 15 },
            { item: 'Contest Token', weight: 1, amount: 90 },
        ],
    }),
    evo_items: new BattleTreeRewardPool({
        id: 'evo_items',
        entries: [
            { item: 'Linking_cord', weight: 1, amount: 1 },
            { item: 'Kings_rock', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.johto) },
            { item: 'Deepsea_scale', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.hoenn) },
            { item: 'Upgrade', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.johto) },
            { item: 'Protector', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.sinnoh) },
            { item: 'Magmarizer', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.sinnoh) },
            { item: 'Whipped_dream', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.kalos) },
            { item: 'Deepsea_tooth', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.hoenn) },
            { item: 'Dragon_scale', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.johto) },
            { item: 'Dubious_disc', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.sinnoh) },
            { item: 'Electirizer', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.sinnoh) },
            { item: 'Reaper_cloth', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.sinnoh) },
            { item: 'Sachet', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.kalos) },
            { item: 'Metal_coat', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.johto) },
            { item: 'Razor_claw', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.sinnoh) },
            { item: 'Razor_fang', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.sinnoh) },
            { item: 'Sweet_apple', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.galar) },
            { item: 'Tart_apple', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.galar) },

            { item: 'Black_augurite', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.hisui) },
            { item: 'Cracked_pot', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.galar) },
            { item: 'Galarica_cuff', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.galar) },
            { item: 'Galarica_wreath', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.galar) },
            { item: 'Leaders_crest', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.paldea) },
            { item: 'Auspicious_armor', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.paldea) },
            { item: 'Malicious_armor', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.paldea) },
            { item: 'Peat_block', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.hisui) },
            { item: 'Syrupy_apple', weight: 1, amount: 1, requirement: new MaxRegionRequirement(Region.paldea) },
        ],
    }),
    shadow_mewtwo: new BattleTreeRewardPool({
        id: 'shadow_mewtwo',
        entries: [
            { item: 'Shadow Mewtwo', weight: 99, amount: 1 },
            { item: 'Shadow_Synergy_Stone', weight: 1, amount: 1 },
        ],
    }),
    venustoise: new BattleTreeRewardPool({
        id: 'venustoise',
        entries: [
            { item: 'Venustoise', weight: 1, amount: 1 },
            { item: 'Battle Point', weight: 99, amount: 100 },
        ],
    }),
    gems: new BattleTreeRewardPool({
        id: 'gems',
        entries: [
            { item: 'Normal Gem', weight: 1, amount: 1000 },
            { item: 'Fire Gem', weight: 1, amount: 1000 },
            { item: 'Water Gem', weight: 1, amount: 1000 },
            { item: 'Electric Gem', weight: 1, amount: 1000 },
            { item: 'Grass Gem', weight: 1, amount: 1000 },
            { item: 'Ice Gem', weight: 1, amount: 1000 },
            { item: 'Fighting Gem', weight: 1, amount: 1000 },
            { item: 'Poison Gem', weight: 1, amount: 1000 },
            { item: 'Ground Gem', weight: 1, amount: 1000 },
            { item: 'Flying Gem', weight: 1, amount: 1000 },
            { item: 'Psychic Gem', weight: 1, amount: 1000 },
            { item: 'Bug Gem', weight: 1, amount: 1000 },
            { item: 'Rock Gem', weight: 1, amount: 1000 },
            { item: 'Ghost Gem', weight: 1, amount: 1000 },
            { item: 'Dragon Gem', weight: 1, amount: 1000 },
            { item: 'Dark Gem', weight: 1, amount: 1000 },
            { item: 'Steel Gem', weight: 1, amount: 1000 },
            { item: 'Fairy Gem', weight: 1, amount: 1000 },
        ],
    }),
};
